config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.views import *
from mailing.apps import MailingConfig

app_name = MailingConfig.name

urlpatterns = [
    path('', cache_page(5)(IndexListView.as_view()), name='index'),

    path('mailing/all/', cache_page(10)(MailingListView.as_view()), name='mailing-all'),
    path('mailing/create/', MailingCreateView.as_view(), name='mailing-create'),
    path('mailing/<int:pk>/', MailingDetailView.as_view(), name='mailing-detail'),
    path('mailing/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing-delete'),
    path('mailing/<int:pk>/update/', MailingUpdateView.as_view(), name='mailing-update'),


    path('client/all/', ClientListView.as_view(), name='client-list'),
    path('client/create/', ClientCreateView.as_view(), name='client-create'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client-detail'),
    path('client/<int:pk>/delete/', ClientDeleteView.as_view(), name='client-delete'),
    path('client/<int:pk>/update/', ClientUpdateView.as_view(), name='client-update'),

    path('blog/all/', BlogListView.as_view(), name='blog-list'),
    path('blog/create/', BlogCreateView.as_view(), name='blog-create'),
    path('blog/<str:slug>/', BlogDetailView.as_view(), name='blog-detail'),
    path('blog/<str:slug>/delete/', BlogDeleteView.as_view(), name='blog-delete'),
    path('blog/<str:slug>/update/', BlogUpdateView.as_view(), name='blog-update'),

    path('messages/', FeedbackListView.as_view(), name='messages'),
    path('feedback-create/', FeedbackCreateView.as_view(), name='feedback-create'),

    path('log/all/', LogSendingListView.as_view(), name='log-all'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.forms import CustomAuthenticationForm
from users.views import CountryCreateView, CountryListView, CountryUpdateView, CountryDetailView, CountryDeleteView, \
    RegisterView, ProfileView, Verification, generate_new_password

from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(form_class=CustomAuthenticationForm, template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('<int:pk>/verification/<int:v_cod>/', Verification.as_view(), name='verification'),
    path('profile/genpassword/', generate_new_password, name='genpassword'),
    path('country/create/', CountryCreateView.as_view(), name='country-create'),
    path('country/<int:pk>/update/', CountryUpdateView.as_view(), name='country-update'),
    path('country/<int:pk>/delete/', CountryDeleteView.as_view(), name='country-delete'),
    path('country/list/', CountryListView.as_view(), name='country-list'),
    path('country/<int:pk>/', CountryDetailView.as_view(), name='country-detail'),
]

mailing/models.py
from django.db import models, transaction
from config.settings import AUTH_USER_MODEL as AU_MODEL


NULLABLE = {'null': True, 'blank': True}


class Client(models.Model):
    email = models.EmailField(verbose_name='email', unique=True)
    fio = models.CharField(max_length=200, verbose_name='ФИО')
    comment = models.TextField(max_length=200, verbose_name='комментарий', **NULLABLE)

    creator = models.ForeignKey(AU_MODEL, on_delete=models.CASCADE, verbose_name='создатель', **NULLABLE)

    def __str__(self):
        return f'{self.fio}: {self.email}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        ordering = ('email', 'fio',)


class Mailing(models.Model):
    INTERVAL_CHOICES = [
        ('D', 'раз в день'),
        ('W', 'раз в неделю'),
        ('M', 'раз в месяц'),
    ]
    STATUS_CHOICES = [
        (1, 'включена'),
        (0, 'отключена'),
    ]

    name = models.CharField(max_length=100, verbose_name='наименование')
    subject = models.CharField(max_length=200, verbose_name='Тема')
    message = models.TextField(verbose_name='Сообщение')

    created_date = models.DateTimeField(verbose_name='дата создания')
    end_date = models.DateTimeField(verbose_name='дата окончания')
    intervals = models.CharField(max_length=1, verbose_name='Периодичность', choices=INTERVAL_CHOICES, default='D')
    status = models.PositiveSmallIntegerField(verbose_name='Статус', choices=STATUS_CHOICES, default=1)

    creator = models.ForeignKey(AU_MODEL, on_delete=models.CASCADE, verbose_name='создатель', **NULLABLE)

    def __str__(self):
        return f'{self.name} {self.subject}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        ordering = ('name',)


class ClientSet(models.Model):
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='рассылка')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='адресат')

    def save(self, *args, **kwargs):
        with transaction.atomic():
            ClientSet.objects.filter(mailing=self.mailing, client=self.client).delete()
        return super(ClientSet, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.mailing} для {self.client}'

    class Meta:
        verbose_name = 'Установленный адресат'
        verbose_name_plural = 'Установленные адресаты'
        ordering = ('mailing',)


class LogSending(models.Model):
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='Рассылка')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='адресат')
    date_time = models.DateTimeField(verbose_name='Последняя попытка')
    status_post = models.CharField(verbose_name='Статус')
    server_request = models.CharField(verbose_name='Ответ сервера')

    creator = models.ForeignKey(AU_MODEL, on_delete=models.CASCADE, verbose_name='создатель', **NULLABLE)

    def __str__(self):
        return f'{self.mailing}: {self.status_post}'

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'
        ordering = ('mailing',)


class Feedback(models.Model):
    name = models.CharField(max_length=150, verbose_name='Имя')
    phone = models.CharField(max_length=25, verbose_name='Телефон')
    email = models.CharField(max_length=100, verbose_name='Почта')
    message = models.TextField(verbose_name='Сообщение')

    def __str__(self):
        return f'{self.name}: {self.message[:30]}'

    class Meta:
        verbose_name = 'Обратная связь'
        verbose_name_plural = 'Обратные связи'
        ordering = ('email',)


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    slug = models.CharField(max_length=200, verbose_name='ЧПУ')
    content = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(upload_to='blogs/', verbose_name='превью', **NULLABLE)
    created_date = models.DateTimeField(verbose_name='дата создания', **NULLABLE)
    is_public = models.BooleanField(default=True, verbose_name='опубликовано или нет')
    views_count = models.IntegerField(default=0, verbose_name='количество просмотров')

    creator = models.ForeignKey(AU_MODEL, on_delete=models.CASCADE, verbose_name='создатель', **NULLABLE)

    def __str__(self):
        return f'{self.title} {self.content[:50]}'

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

mailing/forms.py
from django import forms

from mailing.models import Client, Mailing, Feedback, ClientSet, Blog


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Mailing
        exclude = ['creator']


class ClientForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Client
        exclude = ['creator']


class BlogForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'is_public':
                continue
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Blog
        exclude = ['creator', 'slug', 'views_count', 'created_date']


class FeedbackForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Feedback
        fields = '__all__'


class ClientSetForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = ClientSet
        fields = '__all__'

mailing/views.py
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory
from django.urls import reverse_lazy, reverse
from slugify import slugify

from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from mailing.services import get_blog
from mailing.forms import ClientForm, MailingForm, FeedbackForm, ClientSetForm, BlogForm
from mailing.models import Feedback, Client, Mailing, ClientSet, LogSending, Blog


# Mixin's


class ViewMixin:

    def get_queryset(self):
        queryset = super().get_queryset()

        if self.request.user.is_authenticated:
            if self.request.user.is_staff:
                return queryset
            queryset = queryset.filter(creator=self.request.user)
            return queryset

        queryset = queryset.filter(creator=None)
        return queryset


class CreateMixin:

    def form_valid(self, form):
        self.object = form.save()
        self.object.creator = self.request.user
        self.object.save()

        return super().form_valid(form)


# Index


class IndexListView(ListView):
    model = Blog
    template_name = 'mailing/index.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['rand_blog'] = Blog.objects.order_by('?')[:3]
        context_data['mailing_all'] = Mailing.objects.all().count()
        context_data['mailing_is_activ'] = Mailing.objects.filter(status=1).count()
        context_data['clients'] = Client.objects.all().count()

        return context_data


# Client


class ClientCreateView(CreateMixin, LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client-list')


class ClientUpdateView(UpdateView):
    model = Client
    form_class = ClientForm

    def get_success_url(self):
        return reverse('mailing:client-detail', args=[self.kwargs.get('pk')])


class ClientListView(ViewMixin, ListView):
    model = Client


class ClientDetailView(DetailView):
    model = Client


class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy('mailing:client-list')


# Mailing:


class MailingCreateView(CreateMixin, LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing-all')


class MailingListView(ViewMixin, ListView):
    model = Mailing


class MailingDeleteView(DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailing:mailing-all')


class MailingDetailView(DetailView):
    model = Mailing


class MailingUpdateView(UpdateView):
    model = Mailing
    form_class = MailingForm

    def get_success_url(self):
        return reverse('mailing:mailing-update', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        client_set_formset = inlineformset_factory(Mailing, ClientSet, form=ClientSetForm, extra=1)
        if self.request.method == 'POST':
            formset = client_set_formset(self.request.POST, instance=self.object)
        else:
            formset = client_set_formset(instance=self.object)

        context_data['formset'] = formset

        return context_data

    def form_valid(self, form):

        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


# Feedback


class FeedbackCreateView(CreateView):
    model = Feedback
    form_class = FeedbackForm
    success_url = reverse_lazy('catalog:category')


class FeedbackListView(ListView):
    model = Feedback


# LogSending


class LogSendingListView(ViewMixin, ListView):
    model = LogSending


# Blog:


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('mailing:blog-list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.creator = self.request.user
            new_blog.created_date = datetime.now()
            new_blog.save()
            return super().form_valid(form)


class BlogListView(ListView):
    model = Blog

    def get_queryset(self):
        """Фильтрация по флагу опубликовано"""
        queryset = get_blog()
        queryset = queryset.filter(is_public=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        """Счетчик просмотров"""
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('mailing:blog-list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
            return super().form_valid(form)

    def get_success_url(self):
        new_url = super().get_success_url()[:-4]
        new_url += self.object.slug
        return new_url


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('mailing:blog-list')

mailing/templates/mailing/blog_confirm_delete.html
{% extends 'mailing/base.html' %}

{% load media %}

{% block content %}

    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Удаление!</h1>
            <p class="fs-5 text-body-secondary">Ниже представлена форма для подтверждения удаления.</p>
        </div>
    </header>

    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                                <p>Вы действительно хотите удалить пост? </p>
                                <button type="submit" class="btn btn-danger">Подтвердить</button>
                                <a href="{% url 'mailing:blog-list' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

mailing/templates/mailing/blog_detail.html
{% extends 'mailing/base.html' %}

{% load media %}

{% block content %}

    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Блог</h1>
            <p class="fs-5 text-body-secondary">Ниже представлены сообщения блога.</p>
        </div>
    </header>

    <main class="row">
        <div class="row text-center">

            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">{{ object.title|title }}</h4>
                </div>
                <div class="card-body">
                    <p>
                        {{ object.content }}
                    </p>
                    {% if object.preview %}
                        <img src="{{ object.preview|media_path }}" alt="Изображение - {{ object.title|lower }}">
                    {% endif %}
                    <div class="row">
                        <div class="col-6">
                            <a href="{% url 'mailing:blog-update' object.slug %}" class="w-75 mb-2 btn btn-primary">Редактировать</a>
                        </div>
                        <div class="col-6">
                            <a href="{% url 'mailing:blog-delete' object.slug %}" class="w-75 mb-2 btn btn-danger">Удалить</a>
                        </div>
                    </div>


                </div>

                <div class="card-footer">Просмотры: {{ object.views_count }} </div>
            </div>

        </div>
    </main>
{% endblock %}

mailing/templates/mailing/blog_form.html
{% extends 'mailing/base.html' %}

{% load media %}

{% block content %}

    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <p class="fs-5 text-body-secondary">
                {% if object %}
                    Изменение
                {% else %}
                    Создание
                {% endif %}
                поста.</p>
        </div>
    </header>

    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            {% if object %}
                                <button type="submit" class="btn btn-primary">Изменить</button>
                            {% else %}
                                <button type="submit" class="btn btn-primary">Создать</button>
                            {% endif %}

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

mailing/templates/mailing/blog_list.html
{% extends 'mailing/base.html' %}

{% load media %}

{% block content %}

    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Блог</h1>
            <p class="fs-5 text-body-secondary">Ниже представлены сообщения блога.</p>
        </div>
    </header>

    <main class="row">
        <div class="row text-center">

            {% if object_list %}

                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">№ записи</th>
                        <th scope="col">Название</th>
                        <th scope="col">Содержимое</th>
                        <th scope="col">Ссылка</th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for object in object_list %}

                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ object.title|title }}</td>
                            <td>{{ object.content|truncatechars:20 }}</td>
                            <td>
                                <a href="{% url 'mailing:blog-detail' object.slug %}">Подробнее</a>
                            </td>
                        </tr>

                    {% endfor %}

                    </tbody>
                </table>

            {% else %}

                <p>Данных пока нет, чтобы они появились, пожалуйста, добавьте новую рассылку.</p>

            {% endif %}

            <div class="col-12 mb-5">
                <a class="btn btn-outline-primary" href="{% url 'mailing:blog-create' %}">Добавить пост</a>
            </div>

        </div>
    </main>

{% endblock %}

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/base.html' %}

{% load media %}

{% block content %}

    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Удаление!</h1>
            <p class="fs-5 text-body-secondary">Ниже представлена форма для подтверждения удаления.</p>
        </div>
    </header>

    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                                <p>Вы действительно хотите удалить клиента? </p>
                                <button type="submit" class="btn btn-danger">Подтвердить</button>
                                <a href="{% url 'mailing:client-list' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}

{% load media %}

{% block content %}

    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Клиенты</h1>
            <p class="fs-5 text-body-secondary">
                {% if object_list %}
                    Обзор клиентов для рассылок.
                {% else %}
                    Упс... Список клиентов пуст.
                {% endif %}
            </p>
        </div>
    </header>

    <main class="row">
        <div class="row text-center">

            {% if object_list %}

                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">№ записи</th>
                        <th scope="col">ФИО</th>
                        <th scope="col">Почта</th>
                        <th scope="col">Комментарий</th>
                        <th scope="col">Ссылка</th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for object in object_list %}

                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ object.fio }}</td>
                            <td>{{ object.email }}</td>
                            <td>{{ object.comment }}</td>
                            <td><a href="{% url 'mailing:client-detail' object.pk %}">Подробнее</a></td>
                        </tr>

                    {% endfor %}

                    </tbody>
                </table>

            {% else %}

                <p>Данных пока нет, чтобы они появились, пожалуйста, добавьте нового клиента.</p>

            {% endif %}
        <div class="row text-center">
            <div class="col"><a href="{% url 'mailing:client-create' %}" class="btn btn-outline-primary">Добавить</a></div>
        </div>

        </div>
    </main>
{% endblock %}

mailing/templates/mailing/feedback_form.html
{% extends 'mailing/base.html' %}

{% load media %}

{% block content %}

    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Контакты</h1>
            <p class="fs-5 text-body-secondary">Форма для обратной связи.</p>
            <p>Внимание - все данные в публичном доступе!</p>
        </div>
    </header>

    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            {% if object %}
                                <button type="submit" class="btn btn-primary">Изменить</button>
                            {% else %}
                                <button type="submit" class="btn btn-primary">Создать</button>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

mailing/templates/mailing/feedback_list.html
{% extends 'mailing/base.html' %}

{% load media %}

{% block content %}

    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Сообщения</h1>
            <p class="fs-5 text-body-secondary">Из формы обратной связи.</p>
        </div>
    </header>

    <main class="row">
        <div class="row text-center">

            {% if object_list %}

                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">№ записи</th>
                        <th scope="col">Имя</th>
                        <th scope="col">Телефон</th>
                        <th scope="col">Почта</th>
                        <th scope="col">Сообщение</th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for object in object_list %}

                        <tr>
                            <th scope="row">{{ object.pk }}</th>
                            <td>{{ object.name|title }}</td>
                            <td>{{ object.phone }}</td>
                            <td>{{ object.email }}</td>
                            <td>{{ object.message }}</td>
                        </tr>

                    {% endfor %}

                    </tbody>
                </table>

            {% else %}

                <p>Данных пока нет, чтобы они появились, пожалуйста, заполните форму на странице контакты.</p>

            {% endif %}

        </div>
    </main>

{% endblock %}

mailing/templates/mailing/logsending_list.html
{% extends 'mailing/base.html' %}

{% load media %}

{% block content %}

    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Лог рассылок</h1>
            <p class="fs-5 text-body-secondary">
                {% if object_list %}
                    Просмотр логов.
                {% else %}
                    Упс... Список логов пуст.
                {% endif %}
            </p>
        </div>
    </header>

    <main class="row">
        <div class="row text-center">

            {% if object_list %}

                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">№ записи</th>
                        <th scope="col">Рассылка</th>
                        <th scope="col">Клиент</th>
                        <th scope="col">Последняя попытка</th>
                        <th scope="col">Статус</th>
                        <th scope="col">Ответ сервера</th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for object in object_list %}

                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ object.mailing }}</td>
                            <td>{{ object.client }}</td>
                            <td>{{ object.date_time }}</td>
                            <td>{{ object.status_post }}</td>
                            <td>{{ object.server_request }}</td>
                        </tr>

                    {% endfor %}

                    </tbody>
                </table>

            {% else %}

                <p>Данных пока нет, чтобы они появились, пожалуйста, добавьте новую рассылку.</p>
                <div class="row text-center">
                    <div class="col">
                        <a href="{% url 'mailing:mailing-create' %}" class="btn btn-outline-primary">Добавить</a>
                    </div>
                </div>
            {% endif %}


        </div>
    </main>
{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base.html' %}

{% load media %}

{% block content %}

    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Удаление!</h1>
            <p class="fs-5 text-body-secondary">Ниже представлена форма для подтверждения удаления.</p>
        </div>
    </header>

    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Вы действительно хотите удалить рассылку? </p>
                        <div class="row">
                            <div class="d-grid gap-2 col-6 mx-auto">
                                <button type="submit" class="btn btn-danger">Подтвердить</button>
                            </div>
                            <div class="d-grid gap-2 col-6 mx-auto">
                                <a href="{% url 'mailing:mailing-all' %}" class="btn btn-warning">Отмена</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

mailing/templates/mailing/mailing_detail.html
{% extends 'mailing/base.html' %}

{% load media %}

{% block content %}

    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Рассылка:</h1>
        </div>
    </header>

    <div class="row text-center">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card mb-4">
                <div class="card-header">
                    <h4 class="my-0 fw-normal">{{ object.name }}</h4>
                </div>
                <div class="card-body">

                    <h5>Тема:</h5>
                    <p>{{ object.subject }}</p>

                    <h5>Сообщение:</h5>
                    <p>{{ object.message }}</p>

                    <h5>Статус:</h5>
                    <p>{{ object.get_status_display }}</p>

                    <h5>Периодичность:</h5>
                    <p>{{ object.get_intervals_display }}</p>

                    <h5>Создатель:</h5>
                    <p> {{ object.creator|default:'не указан' }}</p>


                    <div class="card-footer">
                        <div class="row text-center">

                            <div class="col-6">
                                <a href="{% url 'mailing:mailing-update' object.pk %}"
                                   class="btn btn-outline-primary">Редактировать</a>
                            </div>

                            <div class="col-6">
                                <a href="{% url 'mailing:mailing-delete' object.pk %}"
                                   class="btn btn-outline-danger">Удалить</a>
                            </div>

                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}