config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.views import *
from mailing.apps import MailingConfig

app_name = MailingConfig.name

urlpatterns = [
    path('', cache_page(5)(IndexListView.as_view()), name='index'),

    path('mailing/all/', cache_page(10)(MailingListView.as_view()), name='mailing-all'),
    path('mailing/create/', MailingCreateView.as_view(), name='mailing-create'),
    path('mailing/<int:pk>/', MailingDetailView.as_view(), name='mailing-detail'),
    path('mailing/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing-delete'),
    path('mailing/<int:pk>/update/', MailingUpdateView.as_view(), name='mailing-update'),


    path('client/all/', ClientListView.as_view(), name='client-list'),
    path('client/create/', ClientCreateView.as_view(), name='client-create'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='client-detail'),
    path('client/<int:pk>/delete/', ClientDeleteView.as_view(), name='client-delete'),
    path('client/<int:pk>/update/', ClientUpdateView.as_view(), name='client-update'),

    path('blog/all/', BlogListView.as_view(), name='blog-list'),
    path('blog/create/', BlogCreateView.as_view(), name='blog-create'),
    path('blog/<str:slug>/', BlogDetailView.as_view(), name='blog-detail'),
    path('blog/<str:slug>/delete/', BlogDeleteView.as_view(), name='blog-delete'),
    path('blog/<str:slug>/update/', BlogUpdateView.as_view(), name='blog-update'),

    path('messages/', FeedbackListView.as_view(), name='messages'),
    path('feedback-create/', FeedbackCreateView.as_view(), name='feedback-create'),

    path('log/all/', LogSendingListView.as_view(), name='log-all'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.forms import CustomAuthenticationForm
from users.views import CountryCreateView, CountryListView, CountryUpdateView, CountryDetailView, CountryDeleteView, \
    RegisterView, ProfileView, Verification, generate_new_password

from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(form_class=CustomAuthenticationForm, template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('<int:pk>/verification/<int:v_cod>/', Verification.as_view(), name='verification'),
    path('profile/genpassword/', generate_new_password, name='genpassword'),
    path('country/create/', CountryCreateView.as_view(), name='country-create'),
    path('country/<int:pk>/update/', CountryUpdateView.as_view(), name='country-update'),
    path('country/<int:pk>/delete/', CountryDeleteView.as_view(), name='country-delete'),
    path('country/list/', CountryListView.as_view(), name='country-list'),
    path('country/<int:pk>/', CountryDetailView.as_view(), name='country-detail'),
]

mailing/models.py
from django.db import models, transaction
from config.settings import AUTH_USER_MODEL as AU_MODEL


NULLABLE = {'null': True, 'blank': True}


class Client(models.Model):
    email = models.EmailField(verbose_name='email', unique=True)
    fio = models.CharField(max_length=200, verbose_name='ФИО')
    comment = models.TextField(max_length=200, verbose_name='комментарий', **NULLABLE)

    creator = models.ForeignKey(AU_MODEL, on_delete=models.CASCADE, verbose_name='создатель', **NULLABLE)

    def __str__(self):
        return f'{self.fio}: {self.email}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        ordering = ('email', 'fio',)


class Mailing(models.Model):
    INTERVAL_CHOICES = [
        ('D', 'раз в день'),
        ('W', 'раз в неделю'),
        ('M', 'раз в месяц'),
    ]
    STATUS_CHOICES = [
        (1, 'включена'),
        (0, 'отключена'),
    ]

    name = models.CharField(max_length=100, verbose_name='наименование')
    subject = models.CharField(max_length=200, verbose_name='Тема')
    message = models.TextField(verbose_name='Сообщение')

    created_date = models.DateTimeField(verbose_name='дата создания')
    end_date = models.DateTimeField(verbose_name='дата окончания')
    intervals = models.CharField(max_length=1, verbose_name='Периодичность', choices=INTERVAL_CHOICES, default='D')
    status = models.PositiveSmallIntegerField(verbose_name='Статус', choices=STATUS_CHOICES, default=1)

    creator = models.ForeignKey(AU_MODEL, on_delete=models.CASCADE, verbose_name='создатель', **NULLABLE)

    def __str__(self):
        return f'{self.name} {self.subject}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        ordering = ('name',)


class ClientSet(models.Model):
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='рассылка')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='адресат')

    def save(self, *args, **kwargs):
        with transaction.atomic():
            ClientSet.objects.filter(mailing=self.mailing, client=self.client).delete()
        return super(ClientSet, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.mailing} для {self.client}'

    class Meta:
        verbose_name = 'Установленный адресат'
        verbose_name_plural = 'Установленные адресаты'
        ordering = ('mailing',)


class LogSending(models.Model):
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='Рассылка')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='адресат')
    date_time = models.DateTimeField(verbose_name='Последняя попытка')
    status_post = models.CharField(verbose_name='Статус')
    server_request = models.CharField(verbose_name='Ответ сервера')

    creator = models.ForeignKey(AU_MODEL, on_delete=models.CASCADE, verbose_name='создатель', **NULLABLE)

    def __str__(self):
        return f'{self.mailing}: {self.status_post}'

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'
        ordering = ('mailing',)


class Feedback(models.Model):
    name = models.CharField(max_length=150, verbose_name='Имя')
    phone = models.CharField(max_length=25, verbose_name='Телефон')
    email = models.CharField(max_length=100, verbose_name='Почта')
    message = models.TextField(verbose_name='Сообщение')

    def __str__(self):
        return f'{self.name}: {self.message[:30]}'

    class Meta:
        verbose_name = 'Обратная связь'
        verbose_name_plural = 'Обратные связи'
        ordering = ('email',)


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    slug = models.CharField(max_length=200, verbose_name='ЧПУ')
    content = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(upload_to='blogs/', verbose_name='превью', **NULLABLE)
    created_date = models.DateTimeField(verbose_name='дата создания', **NULLABLE)
    is_public = models.BooleanField(default=True, verbose_name='опубликовано или нет')
    views_count = models.IntegerField(default=0, verbose_name='количество просмотров')

    creator = models.ForeignKey(AU_MODEL, on_delete=models.CASCADE, verbose_name='создатель', **NULLABLE)

    def __str__(self):
        return f'{self.title} {self.content[:50]}'

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

mailing/forms.py
from django import forms

from mailing.models import Client, Mailing, Feedback, ClientSet, Blog


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Mailing
        exclude = ['creator']


class ClientForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Client
        exclude = ['creator']


class BlogForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'is_public':
                continue
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Blog
        exclude = ['creator', 'slug', 'views_count', 'created_date']


class FeedbackForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Feedback
        fields = '__all__'


class ClientSetForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = ClientSet
        fields = '__all__'

mailing/views.py
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory
from django.urls import reverse_lazy, reverse
from slugify import slugify

from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from mailing.services import get_blog
from mailing.forms import ClientForm, MailingForm, FeedbackForm, ClientSetForm, BlogForm
from mailing.models import Feedback, Client, Mailing, ClientSet, LogSending, Blog


# Mixin's


class ViewMixin:

    def get_queryset(self):
        queryset = super().get_queryset()

        if self.request.user.is_authenticated:
            if self.request.user.is_staff:
                return queryset
            queryset = queryset.filter(creator=self.request.user)
            return queryset

        queryset = queryset.filter(creator=None)
        return queryset


class CreateMixin:

    def form_valid(self, form):
        self.object = form.save()
        self.object.creator = self.request.user
        self.object.save()

        return super().form_valid(form)


# Index


class IndexListView(ListView):
    model = Blog
    template_name = 'mailing/index.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['rand_blog'] = Blog.objects.order_by('?')[:3]
        context_data['mailing_all'] = Mailing.objects.all().count()
        context_data['mailing_is_activ'] = Mailing.objects.filter(status=1).count()
        context_data['clients'] = Client.objects.all().count()

        return context_data


# Client


class ClientCreateView(CreateMixin, LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client-list')


class ClientUpdateView(UpdateView):
    model = Client
    form_class = ClientForm

    def get_success_url(self):
        return reverse('mailing:client-detail', args=[self.kwargs.get('pk')])


class ClientListView(ViewMixin, ListView):
    model = Client


class ClientDetailView(DetailView):
    model = Client


class ClientDeleteView(DeleteView):
    model = Client
    success_url = reverse_lazy('mailing:client-list')


# Mailing:


class MailingCreateView(CreateMixin, LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing-all')


class MailingListView(ViewMixin, ListView):
    model = Mailing


class MailingDeleteView(DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailing:mailing-all')


class MailingDetailView(DetailView):
    model = Mailing


class MailingUpdateView(UpdateView):
    model = Mailing
    form_class = MailingForm

    def get_success_url(self):
        return reverse('mailing:mailing-update', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        client_set_formset = inlineformset_factory(Mailing, ClientSet, form=ClientSetForm, extra=1)
        if self.request.method == 'POST':
            formset = client_set_formset(self.request.POST, instance=self.object)
        else:
            formset = client_set_formset(instance=self.object)

        context_data['formset'] = formset

        return context_data

    def form_valid(self, form):

        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


# Feedback


class FeedbackCreateView(CreateView):
    model = Feedback
    form_class = FeedbackForm
    success_url = reverse_lazy('catalog:category')


class FeedbackListView(ListView):
    model = Feedback


# LogSending


class LogSendingListView(ViewMixin, ListView):
    model = LogSending


# Blog:


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('mailing:blog-list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.creator = self.request.user
            new_blog.created_date = datetime.now()
            new_blog.save()
            return super().form_valid(form)


class BlogListView(ListView):
    model = Blog

    def get_queryset(self):
        """Фильтрация по флагу опубликовано"""
        queryset = get_blog()
        queryset = queryset.filter(is_public=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        """Счетчик просмотров"""
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('mailing:blog-list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
            return super().form_valid(form)

    def get_success_url(self):
        new_url = super().get_success_url()[:-4]
        new_url += self.object.slug
        return new_url


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('mailing:blog-list')

mailing/templates/mailing/includes/inc_main_menu.html
<div class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark" style="width: 280px;">
    <a href="{% url 'mailing:index' %}"
       class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
        <svg class="bi pe-none me-2" width="40" height="32">
            <use href="#bootstrap"></use>
        </svg>
        <span class="fs-4">Мой сайт.ру</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
            <a href="{% url 'mailing:mailing-all' %}" class="nav-link
                {% if '/mailing/' in request.path %}active{% else %}text-white{% endif %}">
                <svg class="bi pe-none me-2" width="16" height="16">
                    <use href="#home"></use>
                </svg>
                Рассылки
            </a>
        </li>
        <li>
            <a href="{% url 'mailing:client-list' %}" class="nav-link
              {% if '/client/' in request.path %}active{% else %}text-white{% endif %}">
                <svg class="bi pe-none me-2" width="16" height="16">
                    <use href="#table"></use>
                </svg>
                Клиенты
            </a>
        </li>
        <li>
            <a href="{% url 'mailing:log-all' %}" class="nav-link
                {% if '/log/' in request.path %}active{% else %}text-white{% endif %}">
                <svg class="bi pe-none me-2" width="16" height="16">
                    <use href="#collection"></use>
                </svg>
                Лог рассылок
            </a>
        </li>
        <li>
            <a href="{% url 'mailing:blog-list' %}" class="nav-link
              {% if 'blog' in request.path %}active{% else %}text-white{% endif %}">
                <svg class="bi pe-none me-2" width="16" height="16">
                    <use href="#cpu-fill"></use>
                </svg>
                Блог
            </a>
        </li>
        <li>
            <a href="{% url 'users:country-list' %}" class="nav-link
                {% if 'country' in request.path %}active{% else %}text-white{% endif %}">
                <svg class="bi pe-none me-2" width="16" height="16">
                    <use href="#speedometer2"></use>
                </svg>
                Страны
            </a>
        </li>
        <li>
            <a href="{% url 'mailing:messages' %}" class="nav-link
                {% if request.path == '/messages/' %}active{% else %}text-white{% endif %}">
                <svg class="bi pe-none me-2" width="16" height="16">
                    <use href="#grid"></use>
                </svg>
                Сообщения FB
            </a>
        </li>
        <li>
            <a href="{% url 'mailing:feedback-create' %}" class="nav-link
                {% if request.path == '/feedback-create/' %}active{% else %}text-white{% endif %}">
                <svg class="bi pe-none me-2" width="16" height="16">
                    <use href="#people-circle"></use>
                </svg>
                Контакты
            </a>
        </li>
    </ul>
    <hr>
    <div class="dropdown">
        <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
           data-bs-toggle="dropdown" aria-expanded="false">
            <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
            <strong>
                {% if user.is_authenticated %}
                    {% if user.first_name %}
                        {{ user.first_name }}
                    {% elif user.last_name %}
                        {{ user.last_name }}
                    {% else %}
                        {{ user.email }}
                    {% endif %}
                {% else %}
                    Аутентификация
                {% endif %}
            </strong>
        </a>
        <ul class="dropdown-menu dropdown-menu-dark text-small shadow">

            {% if user.is_authenticated %}
                <li><a class="dropdown-item" href="{% url 'admin:index' %}">Админка</a></li>
                <li><a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a></li>
            {% else %}
                <li><a class="dropdown-item" href="{% url 'users:login' %}">Войти</a></li>
            {% endif %}

            <li>
                <hr class="dropdown-divider">
            </li>

            <li>
                {% if user.is_authenticated %}
                    <a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a>
                {% else %}
                    <a class="dropdown-item" href="{% url 'users:register' %}">Регистрация</a>
                {% endif %}
            </li>
        </ul>
    </div>
</div>